
IF
 True()
THEN
 RESPONSE #100
    CutSceneID(Player1)
    SetGlobal("RJTaliraRomance","GLOBAL",4)
    OpenDoor("DOOR11")
    Wait(1)
    ApplySpellRES("RJUNHIDE","RJFAY") 
    ApplySpellRES("RJUNHIDE",Player2)
    ApplySpellRES("RJUNHIDE",Player3)
    ApplySpellRES("RJUNHIDE",Player4)
    ApplySpellRES("RJUNHIDE",Player5)
    ApplySpellRES("RJUNHIDE",Player6)
    Wait(2)
    DisplayStringHead("Rjali",@2003)
    Wait(2)
    EndCutSceneMode()
END
