
IF
InParty(Myself)
G("RjaliNindeStuff",0)
G("RjaliEquips",0)
G("RjaliMet",3)
OR(5)
  InPartySlot("Ninde",1)
  InPartySlot("Ninde",2)
  InPartySlot("Ninde",3)
  InPartySlot("Ninde",4)
  InPartySlot("Ninde",5)
!StateCheck("Ninde",CD_STATE_NOTVALID)
THEN
RESPONSE #100
MoveToObjectNoInterrupt("Ninde")
FaceObject("Ninde")
SetGlobal("RjaliNindeStuff","GLOBAL",1)
SetToken("RJEQUIP",@9)
SetGlobal("RjaliEquips","GLOBAL",1)
END
