
IF
InParty(Myself)
G("RjaliKesaiStuff",0)
G("RjaliEquips",0)
G("RjaliMet",3)
OR(5)
  InPartySlot("RJKesai",1)
  InPartySlot("RJKesai",2)
  InPartySlot("RJKesai",3)
  InPartySlot("RJKesai",4)
  InPartySlot("RJKesai",5)
!StateCheck("RJKesai",CD_STATE_NOTVALID)
THEN
RESPONSE #100
MoveToObjectNoInterrupt("RJKesai")
FaceObject("RJKesai")
SetGlobal("RjaliKesaiStuff","GLOBAL",1)
SetToken("RJEQUIP",@47)
SetGlobal("RjaliEquips","GLOBAL",1)
END
