
IF
InParty(Myself)
G("RjaliSireneStuff",0)
G("RjaliEquips",0)
G("RjaliMet",3)
OR(5)
  InPartySlot("C0Sirene",1)
  InPartySlot("C0Sirene",2)
  InPartySlot("C0Sirene",3)
  InPartySlot("C0Sirene",4)
  InPartySlot("C0Sirene",5)
!StateCheck("C0Sirene",CD_STATE_NOTVALID)
THEN
RESPONSE #100
MoveToObjectNoInterrupt("C0Sirene")
FaceObject("C0Sirene")
SetGlobal("RjaliSireneStuff","GLOBAL",1)
SetToken("RJEQUIP",@44)
SetGlobal("RjaliEquips","GLOBAL",1)
END
