
IF
InParty(Myself)
G("RjaliAmberStuff",0)
G("RjaliEquips",0)
G("RjaliMet",3)
OR(5)
  InPartySlot("M#AMBER",1)
  InPartySlot("M#AMBER",2)
  InPartySlot("M#AMBER",3)
  InPartySlot("M#AMBER",4)
  InPartySlot("M#AMBER",5)
!StateCheck("M#AMBER",CD_STATE_NOTVALID)
THEN
RESPONSE #100
MoveToObjectNoInterrupt("M#AMBER")
FaceObject("M#AMBER")
SetGlobal("RjaliAmberStuff","GLOBAL",1)
SetToken("RJEQUIP",@30)
SetGlobal("RjaliEquips","GLOBAL",1)
END
